### PR TITLE
fix: update jjwt version

### LINKED ISSUE #788: Update JJWT Dependency
### Issue Summary
I am currently running into dependency incompatibility issues between this library and the Okta one. Both libraries utilize the jjwt-api/jjwt-impl libraries which are currently on 0.12.5 and includes some breaking changes in 0.12.#+. The latest version of the Okta library utilizes 0.12.3 while this library is still using 0.11.2 and are incompatible with each other.

I attempted to update the Okta one to the latest in order to address vulnerabilities that came with some of the other dependencies it has but ran into issues with differences between the jjwt versions. Unfortunately, this has me in a position where I cannot actually do that until this library also updates to 0.12.#+.

My request is for the jjwt libraries that are being used be updated to at least 0.12.0.

### Technical details:
* twilio-java version: 10.1.3
* java version: 21

### PR DESCRIPTION
**Pull request by manisha1997**
# Fixes #788 

JJWT version updated to 0.12.6

Summary
------------
From JJWT version 0.12.0, when Content-type is set, the payload is no longer extracting claims by default
For discussion, https://github.com/jwtk/jjwt/issues/897
https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.10

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-java/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Review by kridai — APPROVED** [review]

File: src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java [hunk 1]
```diff
@@ -76,8 +78,18 @@ public void setup() throws Exception {
         publicKey = pair.getPublic();
     }
 
+    private Claims getClaimFromJwtToken(Jwt token) throws IOException {
```
Comment (tiwarishubham635) [inline src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java:81]: Correct me if I am wrong, but the reason why this function getClaimFromJwtToken is different from the [getClaims()](https://github.com/twilio/twilio-java/blob/update-jwt-version/src/test/java/com/twilio/jwt/taskrouter/TaskRouterCapabilityTest.java#L47-L54) is because here we are using PublicKey as the signing key while in getClaims() we use private key right? Can we right this as an inline documentation so that we get more clarity about these tests? Thanks!

**Review by tiwarishubham635 — APPROVED** [review]
LGTM! I have added a couple of comments for inline documentation. It would be better if we can add them. Thanks!

File: src/main/java/com/twilio/example/AccessTokenExample.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+    String token = accessToken.toJwt();
+
+    // create JSON response payload
+    HashMap<String, String> json = new HashMap<>();
+    json.put("identity", randomIdentity);
+    json.put("token", token);
+
+    Gson gson = new Gson();
+    System.out.println(gson.toJson(json));
```
Comment (tiwarishubham635) [inline src/main/java/com/twilio/example/AccessTokenExample.java:36]: Since this is part of our package, instead of print statement can we add logger? Or maybe move this to [examples folder](https://github.com/twilio/twilio-java/tree/update-jwt-version/examples)?

File: src/main/java/com/twilio/example/AccessTokenExample.java [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+    // Create Voice grant
+    VoiceGrant grant = new VoiceGrant();
+    grant.setOutgoingApplicationSid(applicationSid);
+
+    // Optional: add to allow incoming calls
+    grant.setIncomingAllow(true);
+
+    String randomIdentity = "random-identity";
+    // Create access token
+    AccessToken accessToken = new AccessToken.Builder(acctSid, apiKey, apiSecret.getBytes())
```
[the remark this answers is not in the document]
Comment (manisha1997) [reply src/main/java/com/twilio/example/AccessTokenExample.java:23]: added in CHANGES.md

File: src/main/java/com/twilio/example/AccessTokenExample.java (hunk 2 above)
Comment (manisha1997) [reply src/main/java/com/twilio/example/AccessTokenExample.java:36]: I used the template of ValidationExample.java
