### PR TITLE
fix: paging breaks with + sign on phone number

### LINKED ISSUE #569: Paging breaks when filtering with To number with + sign
### Issue Summary

When filtering a list of calls or messages by the to/from number, when including the leading `+` (E.164 format) the auto-paging breaks.

### Steps to Reproduce
1. Get a number with more than 5 calls
2. Plug it into my example code.

### Code Snippet
```java
import com.google.common.collect.Iterators;
import com.twilio.Twilio;
import com.twilio.base.ResourceSet;
import com.twilio.rest.api.v2010.account.Call;

public class ReproduceTwilioBug {

    static {
        Twilio.init("xxx", "yyy");
    }

    public static void main(final String args[]) {
        final String to = "+1843xxxx";
        countCalls(to);
        countCalls(to.replace("+", ""));
    }

    static void countCalls(final String to) {
        ResourceSet<Call> calls = Call.reader().setTo(to).pageSize(5).limit(20).read();
        System.out.println("For " + to + " " + Iterators.size(calls.iterator()) + " calls.");
    }
}

```
This outputs

```
For +1843xxxx 5 calls.
For 1843xxxx 20 calls.
```

It's able to download the first page, but when it gets to page 2 (`Page=1&PageToken=PG...`) I get back `calls: []` in the JSON. When I step through with the debugger the URL looks correct, and querying that URL with different HTTP clients (Insomnia, curl) returns the call records. I suspect the `+` is getting encoded into `%2B` too early and then getting encoded again.

### Technical details:
* twilio-java version: 7.55.0
* java version: Adopt JDK 1.11.0-6

### PR DESCRIPTION
**Pull request by thinkingserious**
Fixes #569

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by thinkingserious** [comment]
This was how I reproduced #569:

```bash
git clone https://github.com/twilio/twilio-java.git
cd twilio-java
touch ReproduceTwilioBug.java
```

`ReproduceTwilioBug.java`:

```java
import com.google.common.collect.Iterators;
import com.twilio.Twilio;
import com.twilio.base.ResourceSet;
import com.twilio.rest.api.v2010.account.Call;

public class ReproduceTwilioBug {

    static {
        String accountSid = System.getenv("TWILIO_ACCOUNT_SID");
        String authToken = System.getenv("TWILIO_AUTH_TOKEN");
        Twilio.init(accountSid, authToken);
    }

    public static void main(final String args[]) {
        String toPhoneNumber = System.getenv("TWILIO_TO_PHONE_NUMBER");
        final String to = toPhoneNumber;
        countCalls(to);
        countCalls(to.replace("+", ""));
    }

    static void countCalls(final String to) {
        ResourceSet<Call> calls = Call.reader().setTo(to).pageSize(5).limit(20).read();
        System.out.println("For " + to + " " + Iterators.size(calls.iterator()) + " calls.");
    }
}
```

```bash
mvn install -DskipTests
javac -classpath ./target/twilio-7.55.0-jar-with-dependencies.jar:. ReproduceTwilioBug.java && java -classpath ./target/twilio-7.55.0-jar-with-dependencies.jar:. ReproduceTwilioBug
```

Result:
```bash
For +1951XXXXXXX 5 calls.
For 1951XXXXXXX 6 calls.
```

After this fix, Result:
```bash
For +1951XXXXXXX 6 calls.
For 1951XXXXXXX 6 calls.
```

File: src/main/java/com/twilio/http/Request.java [hunk 1]
```diff
@@ -285,7 +285,12 @@ private static String encodeParameters(final Map<String, List<String>> params) {
                         continue;
                     }
 
-                    String encodedValue = URLEncoder.encode(value, "UTF-8");
+                    String encodedValue;
+                    if (value.startsWith("+")) {
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:289]: This is not the proper solution and there are many other characters which this would not solve for. Proper changes are needed in `com.twilio.http.Request.buildURL()`

**Comment by childish-sambino** [comment]
Is there any overlap with https://github.com/twilio/twilio-java/issues/570?

File: src/main/java/com/twilio/http/Request.java (hunk 1 above)
Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java:289]: `buildURL()` appears to be constructing the URL properly (I compared the current method with the method prior to #558). The issue seems to be within `encodeParameters()` where each parameter is encoded. In the case of a phone number, it appears we should not encode the + sign. `contructURL()` is where we add the parameters to the final URL.

Comment (childish-sambino) [reply src/main/java/com/twilio/http/Request.java:289]: The first page works fine which is where `encodeParameters` is called. The second page fails because `buildURL` is re-encoding the already-encoded parameters.

**Comment by thinkingserious** [comment]
#570 seems related to not handling non-JSON return values when paging fails. To be sure, I'd like to reproduce that one as well.

File: src/main/java/com/twilio/http/Request.java (hunk 1 above)
Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java]: I'm not seeing where `buildURL` is re-encoding the parameters. Might be easier to talk through it?

I added code to decode each value first before encoding. That seems to work locally, checking tests.

File: src/main/java/com/twilio/http/Request.java [hunk 2]
```diff
@@ -174,9 +174,14 @@ private String buildURL() {
...
-
-            return new URI(parsedUrl.getProtocol(), parsedUrl.getUserInfo(), host, parsedUrl.getPort(),
-                    parsedUrl.getPath(), parsedUrl.getQuery(), parsedUrl.getRef()).toURL().toString();
+            String getQuery = "";
+            if( parsedUrl.getQuery() != null ) {
+                getQuery = "?" + parsedUrl.getQuery();
+            }
+            String constructedURI = new URI(
+                    parsedUrl.getProtocol(), parsedUrl.getUserInfo(), host, parsedUrl.getPort(),
+                    parsedUrl.getPath(), null, parsedUrl.getRef()).toString() + getQuery;
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:183]: https://en.wikipedia.org/wiki/URI_fragment
> The fragment identifier introduced by a hash mark `#` is the optional last part of a URL for a document.

This places it _before_ the query.

What about just decoding the query part before constructing the URI?

File: src/main/java/com/twilio/http/Request.java [hunk 3]
```diff
@@ -174,9 +174,18 @@ private String buildURL() {
...
+                getQuery = "?" + parsedUrl.getQuery();
+            }
+            String getFragment = "";
+            if( parsedUrl.getRef() != null ) {
+                getFragment = "#" + parsedUrl.getRef();
+            }
+            String constructedURI = new URI(
+                    parsedUrl.getProtocol(), parsedUrl.getUserInfo(), host, parsedUrl.getPort(),
+                    parsedUrl.getPath(), null,null).toString() + getQuery + getFragment;
+            return new URI(constructedURI).toString();
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:188]: `new URI().toString()` from a `new URI().toString()`? This looks even more overly-complicated. Can we just drop the usage of `URI` and construct the URL similar to what we do in other languages?

Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java:188]: I'll give constructing the URL manually a shot.

File: src/main/java/com/twilio/http/Request.java [hunk 4]
```diff
@@ -284,7 +299,6 @@ private static String encodeParameters(final Map<String, List<String>> params) {
                     if (value == null) {
                         continue;
                     }
-
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:287]: Nooooooooo

File: src/main/java/com/twilio/http/Request.java [hunk 5]
```diff
@@ -175,9 +175,24 @@ private String buildURL() {
                 host = joinIgnoreNull(".", product, targetEdge, targetRegion, domain);
             }
 
-            return new URI(parsedUrl.getProtocol(), parsedUrl.getUserInfo(), host, parsedUrl.getPort(),
-                    parsedUrl.getPath(), parsedUrl.getQuery(), parsedUrl.getRef()).toURL().toString();
-        } catch (final MalformedURLException | URISyntaxException e) {
+            int port = -1;
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:178]: This var isn't needed.

File: src/main/java/com/twilio/http/Request.java [hunk 6]
```diff
@@ -175,9 +175,24 @@ private String buildURL() {
...
+            String path = parsedUrl.getPath().replace("|", "%7C");
+            String query = null;
+            if (parsedUrl.getQuery() != null) {
+                query = "?" + parsedUrl.getQuery();
+            }
+            String ref = null;
+            if (parsedUrl.getRef() != null) {
+                ref = "#" + parsedUrl.getRef();
+            }
+            return joinIgnoreNull("", protocol, host, urlPort, path, query, ref);
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:194]: Does this handle URLs with embedded credentials.

File: src/main/java/com/twilio/http/Request.java [hunk 7]
```diff
@@ -175,9 +175,24 @@ private String buildURL() {
...
-                    parsedUrl.getPath(), parsedUrl.getQuery(), parsedUrl.getRef()).toURL().toString();
-        } catch (final MalformedURLException | URISyntaxException e) {
+            int port = -1;
+            String urlPort = null;
+            if (parsedUrl.getPort() != -1) {
+                port = parsedUrl.getPort();
+                urlPort = ":" + port;
+            }
+            String protocol = parsedUrl.getProtocol() + "://";
+            String path = parsedUrl.getPath().replace("|", "%7C");
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:185]: This needs to use a proper encoder. There are many other characters that it would cover.

File: src/main/java/com/twilio/http/Request.java (hunk 6 above)
Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java]: Now it does. Great catch!

File: pom.xml [hunk 8]
```diff
@@ -228,6 +228,11 @@
       <version>3.4.1</version>
       <scope>test</scope>
     </dependency>
+    <dependency>
+      <groupId>commons-lang</groupId>
+      <artifactId>commons-lang</artifactId>
+      <version>2.4</version>
+    </dependency>
```
Comment (childish-sambino) [inline pom.xml:235]: I don't like adding new dependencies when existing dependencies will do the job.

Comment (thinkingserious) [reply pom.xml:235]: Ah, we can use the Guava Joiner for now and then we switch it out after dropping support for Java 7. Good catch, thanks!

File: src/main/java/com/twilio/http/Request.java [hunk 9]
```diff
@@ -175,9 +176,28 @@ private String buildURL() {
...
+                urlPort = ":" + parsedUrl.getPort();
+            }
+            String protocol = parsedUrl.getProtocol() + "://";
+            String[] pathPieces = parsedUrl.getPath().split("/", 0);
+            pathPieces[pathPieces.length-1] = URLEncoder.encode(pathPieces[pathPieces.length-1], "UTF-8");
+            String encodedPath = Joiner.on("/").join(pathPieces);
+            String query = null;
+            if (parsedUrl.getQuery() != null) {
+                query = "?" + parsedUrl.getQuery();
+            }
```
Comment (eshanholtz) [inline src/main/java/com/twilio/http/Request.java:190]: Simplify these for readability: `String query = parsedUrl.getQuery() != null ? "?" + parsedUrl.getQuery() : null;`

File: src/main/java/com/twilio/http/Request.java [hunk 10]
```diff
@@ -175,9 +176,19 @@ private String buildURL() {
...
-            return new URI(parsedUrl.getProtocol(), parsedUrl.getUserInfo(), host, parsedUrl.getPort(),
-                    parsedUrl.getPath(), parsedUrl.getQuery(), parsedUrl.getRef()).toURL().toString();
-        } catch (final MalformedURLException | URISyntaxException e) {
+            String urlPort = null;
+            if (parsedUrl.getPort() != -1) {
+                urlPort = ":" + parsedUrl.getPort();
+            }
+            String protocol = parsedUrl.getProtocol() + "://";
+            String[] pathPieces = parsedUrl.getPath().split("/", 0);
+            pathPieces[pathPieces.length-1] = URLEncoder.encode(pathPieces[pathPieces.length-1], "UTF-8");
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:185]: I don't understand this `pathPieces` logic. Needs a comment.

File: src/main/java/com/twilio/http/Request.java [hunk 11]
```diff
@@ -175,9 +176,19 @@ private String buildURL() {
...
+            String encodedPath = Joiner.on("/").join(pathPieces);
+            String query = parsedUrl.getQuery() != null ? "?" + parsedUrl.getQuery() : null;
+            String ref = parsedUrl.getRef() != null ? "#" + parsedUrl.getRef() : null;
+            String credentials  = parsedUrl.getUserInfo() != null ? parsedUrl.getUserInfo() + "@" : null;
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:189]: Spacing looks off. Are you using IntelliJ to format?

File: src/main/java/com/twilio/http/Request.java (hunk 10 above)
Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java:186]: Comment added. The idea is to only encode the path portion of the URL.

File: src/main/java/com/twilio/http/Request.java (hunk 11 above)
Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java]: Nice! The formatter caught a stray space after `credentials`.

File: src/main/java/com/twilio/http/Request.java [hunk 12]
```diff
@@ -175,9 +176,20 @@ private String buildURL() {
...
 
-            return new URI(parsedUrl.getProtocol(), parsedUrl.getUserInfo(), host, parsedUrl.getPort(),
-                    parsedUrl.getPath(), parsedUrl.getQuery(), parsedUrl.getRef()).toURL().toString();
-        } catch (final MalformedURLException | URISyntaxException e) {
+            String urlPort = null;
+            if (parsedUrl.getPort() != -1) {
+                urlPort = ":" + parsedUrl.getPort();
+            }
+            String protocol = parsedUrl.getProtocol() + "://";
+            String[] pathPieces = parsedUrl.getPath().split("/", 0);
```
Comment (childish-sambino) [inline src/main/java/com/twilio/http/Request.java:184]: Default limit is already `0` so second arg not needed.

File: src/main/java/com/twilio/http/Request.java (hunk 10 above)
Comment (childish-sambino) [reply src/main/java/com/twilio/http/Request.java:186]: So if you have `/foo|bar/baz|qux` only `baz/qux` gets encoded?

Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java:186]: Yes, `baz|qux` would only be encoded. Based on our tests, I'm assuming this case does not happen. If we do expect that use case, then perhaps we should encode all pieces of the path, save `/` characters.

Comment (childish-sambino) [reply src/main/java/com/twilio/http/Request.java:186]: We don't control where the characters needing encoding would be. Best to encode them all.

Comment (thinkingserious) [reply src/main/java/com/twilio/http/Request.java]: Updated

**Review by childish-sambino — APPROVED** [review]

File: src/main/java/com/twilio/http/Request.java [hunk 13]
```diff
@@ -175,9 +176,21 @@ private String buildURL() {
                 host = joinIgnoreNull(".", product, targetEdge, targetRegion, domain);
             }
 
-            return new URI(parsedUrl.getProtocol(), parsedUrl.getUserInfo(), host, parsedUrl.getPort(),
-                    parsedUrl.getPath(), parsedUrl.getQuery(), parsedUrl.getRef()).toURL().toString();
-        } catch (final MalformedURLException | URISyntaxException e) {
+            String urlPort = null;
+            if (parsedUrl.getPort() != -1) {
+                urlPort = ":" + parsedUrl.getPort();
+            }
```
Comment (eshanholtz) [inline src/main/java/com/twilio/http/Request.java:182]: Could do one more simplification here similar to below:
`String urlPort = parsedUrl.getPort() != -1 ? ":" + parsedUrl.getPort() : null;`

**Review by eshanholtz — APPROVED** [review]
